install.packages("dplyr")
install.packages("httr")
install.packages("jsonlite")
install.packages("vader")
install.packages("stringr")
install.packages("xlsx")
install.packages("ggplot2")
install.packages("rcompanion")

library(dplyr)
library(httr)
library(jsonlite)
library(vader)
library(stringr)
library(xlsx)
library(ggplot2)
library(rcompanion)

source("scripts/data_retrival.R")
source("scripts/data_processing.R")
